### ISSUE TITLE
Reduce the monitoring period to 8 hours.

### ISSUE THREAD

**Issue by Munkenmo** [jack-webb/reddit-submision-limiter#10]
The bot is creating modqueue lists >60 entries long multiple times a day.  At the moment, it's more effort than it's worth.

I'd like to propose that we lower the bot to only monitor an 8 hour period, in order to reduce the work it's creating and still catch problem users that are spamming questions too frequently.

**Comment by jack-webb** [comment]
Config change request - n/a for this repository. Have made the change on our instance, though :)
